### ISSUE TITLE
Extend Documentation section with some basic resources

### ISSUE THREAD

**Issue by zelyanovskyy** [sjcbulldog/mtbassist#10]
Please add following links for the "ModusToolbox Documentation":
1. "Training Materials" pointing to https://github.com/Infineon/training-modustoolbox
2. "Visual Studio Code for ModusToolbox™ user guide" pointing to https://www.infineon.com/MTBVSCodeUserGuide

I think these links should be there regardless if a folder is open or not.

**Comment by mindxing** [comment]
There is already a "Visual Studio For ModusToolbox User's Guide" link on the documentation tab. Is what you're proposing in this issue a different link?

**Comment by zelyanovskyy** [comment]
Yes, I am proposing it to be in the ModusToolbox Documentation group of the extension view on the left.

**Comment by sjcbulldog** [comment]
Done as of version 1.2.3
