### ISSUE TITLE
Unable to find installed tools

### ISSUE THREAD

**Issue by Panometric** [sjcbulldog/mtbassist#5]
Using vscode 1.81.1, I have 3 versions of Modustoolbox installed:

```
>dir %USERPROFILE%\ModusToolbox
08/21/2023  05:52 PM    <DIR>          .
08/21/2023  05:52 PM    <DIR>          ..
10/06/2021  04:28 PM            12,675 CYPRESS END USER LICENSE AGREEMENT 2.4.txt
09/27/2022  05:03 PM            12,762 CYPRESS END USER LICENSE AGREEMENT 3.0.txt
05/30/2023  03:00 PM            12,762 CYPRESS END USER LICENSE AGREEMENT 3.1.txt
11/22/2021  04:11 PM    <DIR>          docs_2.4
11/24/2022  11:28 AM    <DIR>          docs_3.0
08/21/2023  05:52 PM    <DIR>          docs_3.1
12/16/2021  05:13 PM    <DIR>          ide_2.4
11/24/2022  11:26 AM    <DIR>          ide_3.0
08/21/2023  05:50 PM    <DIR>          ide_3.1
11/22/2021  04:11 PM    <DIR>          tools_2.4
11/24/2022  11:28 AM    <DIR>          tools_3.0
08/21/2023  05:52 PM    <DIR>          tools_3.1
08/21/2023  05:52 PM    <DIR>          uninstallers
11/22/2021  04:11 PM             1,049 unins_2.4.lnk
11/24/2022  11:28 AM             1,049 unins_3.0.lnk
08/21/2023  05:52 PM             1,049 unins_3.1.lnk

```

But I get this error:

> ModusToolbox Assistant 1.0.26
> 
> The ModusToolbox Assistant extension is designed to be used with ModusToolbox 3.0 or later. However, ModusToolbox 3.0 or later is not installed. Please install ModusToolbox 3.0 or later to use this extensison.
> 
> [Click Here To Download ModusToolbox](https://www.infineon.com/cms/en/design-support/tools/sdk/modustoolbox-software/)

**Comment by Panometric** [comment]
Thanks. I did have CY_TOOLS_PATHS set and it fails when set to 2.4, but not when set to 3.1

But I am unable to turn on debugging when set to 2.4:
![image](https://github.com/sjcbulldog/mtbassist/assets/716218/0da6279e-8f8f-40c9-aed1-557d38786270)

Ironically I can turn on debugging when set to 3.1

We can close this for me, but it does seem like it should know if the CY_TOOLS_PATHS is set incorrectly or at least tell in the error message.

**Comment by sjcbulldog** [comment]
We are strongly recommending a 3.x version of ModusToolbox.  Going to close this.
