### ISSUE TITLE
Startup sequence needs to be more obvious

### ISSUE THREAD

**Issue by sjcbulldog** [sjcbulldog/mtbassist#7]
The extension determines if 'make getlibs' or 'make vscode' is required and does the right thing.  However, it is not obvious that the extension is doing this and these operations take a while depending on the speed of the internet connection.  The extension should make it more obvious what it is doing and when it is ready for the user.

**Comment by inf-wehale** [comment]
I believe I have addressed this in https://github.com/sjcbulldog/mtbassist/pull/12, I added a simple progress indicator to MTBExtensionInfo.updateStatusBar() so that it shows a spinning wheel while long running operations are in progress.

**Comment by sjcbulldog** [comment]
I have updated this to use the vscode.window.withProgress to report on what is happening as well as showing a continually running progress bar until the ModusToolbox project is ready for use.
